version: 2.1
jobs:
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
